### PR TITLE
Drop gray-matter from client bundle

### LINKED ISSUE #1630: Server-side code of `gray-matter` package in client bundle
**Describe the bug**
`gray-matter` package runs only on the server in `getStaticProps`, but it unexpectedly is included in client js bundle.

**To Reproduce**
You can check it with bundle-analyzer or statoscope by running npm script `build:analyze`.

**Expected behavior**
`gray-matter` package is removed from client bundle.

### PR DESCRIPTION
**Pull request by KateKate**
## PR includes

- [X] Refactor

It reduces client js bundle by ~ 50Kb gzip.

## Related issues

Resolve #1630

### CODE REVIEW

**Comment by KateKate** [comment]
The fix is only to move getStaticProps inside "page" file - drop `export { getStaticProps }`.

**Comment by awinogradov** [comment]
@KateKate https://github.com/taskany-inc/issues/actions/runs/6097924218/job/16546594793?pr=1631#step:3:136

**Comment by KateKate** [comment]
> @KateKate https://github.com/taskany-inc/issues/actions/runs/6097924218/job/16546594793?pr=1631#step:3:136

fixed

**Comment by awinogradov** [comment]
> fixed

U need to push it ;)

**Comment by KateKate** [comment]
> > fixed
> 
> U need to push it ;)

image

**Review by awinogradov — APPROVED** [review]

**Review by 9teen90nine — APPROVED** [review]

**Pull request merged**
