### PR TITLE
chore: always use react strict mode

### PR DESCRIPTION
**Pull request by KateKate**
## PR includes

- [X] DX

### CODE REVIEW

**Review by 9teen90nine — APPROVED** [review]

**Review by 9teen90nine — CHANGES_REQUESTED** [review]
Branch title and PR header don't pass contribution guide

**Comment by KateKate** [comment]
> Branch title and PR header don't pass contribution guide

Could you plz elaborate. Do you want me to change branch name `speed/strict-mode` => `issues/strict-mode`? according to [docs](https://github.com/taskany-inc/issues/blob/main/CONTRIBUTING.md#:~:text=Create%20a%20new%20branch%20based%20off%20the%20master%20branch.%20Branch%20name%20must%20follow%20pattern%20issues/%7Bid%7D%3B)

And I didn't get the comment about PR header.

Thanks in advance

**Comment by 9teen90nine** [comment]
You should first create an issue  describing the problem you're trying to fix and then put the issue header in the PR title field.

**Comment by KateKate** [comment]
> You should first create an issue describing the problem you're trying to fix and then put the issue header in the PR title field.

I've fixed it in [another PR](https://github.com/taskany-inc/issues/pull/1405), this PR will be closed.

**Pull request closed without merging**
